inherit_from:
- .rubocop_airbnb.yml

AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'bin/**/*'
  - 'vendor/**/*'
  - 'Gemfile'
  - 'lib/tasks/_force_reload.rake'

Airbnb/OptArgParameters:
  Exclude:
  - 'app/helpers/application_helper.rb'
